const jogos = [
    {
        "Ano": 1958,
        "Jogo": "Tennis for Two",
        "HistoriaResumida": "Simula uma partida de tênis em um osciloscópio.",
        "MotivoDaCriacao": "Criado por William Higinbotham para entreter visitantes em um laboratório.",
        "MecanicasPrincipais": "Física básica de movimento e colisão.",
        "InovacoesTecnologicas": "Primeiro jogo eletrônico interativo com visual gráfico.",
        "ImpactoCulturalOuComercial": "Primeiro jogo eletrônico interativo",
        "Genero": "Simulação esportiva",
        "ErasGeracoes": "Pré-história dos games",
        "Imagem": "https://www.oldbits.com.br/images/artigos/Tenis_for_two.gif"
    },
    {
        "Ano": 1962,
        "Jogo": "Spacewar!",
        "HistoriaResumida": "Combate espacial entre duas naves em gravidade simulada.",
        "MotivoDaCriacao": "Desenvolvido por estudantes do MIT como demonstração de programação.",
        "MecanicasPrincipais": "Controle de nave, tiro, gravidade.",
        "InovacoesTecnologicas": "Um dos primeiros jogos multiplayer em rede.",
        "ImpactoCulturalOuComercial": "Um dos primeiros jogos multiplayer",
        "Genero": "Shooter espacial",
        "ErasGeracoes": "Pré-história dos games",
        "Imagem": "https://i.makeagif.com/media/9-24-2015/P4kTyk.gif"
    },
    {
        "Ano": 1971,
        "Jogo": "Computer Space",
        "HistoriaResumida": "Versão comercial de Spacewar!, com gráficos em arcade.",
        "MotivoDaCriacao": "Criado por Nolan Bushnell como primeiro arcade comercial.",
        "MecanicasPrincipais": "Movimento, tiro, pontuação.",
        "InovacoesTecnologicas": "Primeiro arcade comercial da história.",
        "ImpactoCulturalOuComercial": "Primeiro arcade comercial",
        "Genero": "Shooter espacial",
        "ErasGeracoes": "Era Arcade",
        "Imagem": "https://thedoteaters.com/tde/wp-content/uploads/2013/03/cspace-feat-computer-space.gif"
    },
    {
        "Ano": 1972,
        "Jogo": "Pong",
        "HistoriaResumida": "Simula tênis de mesa com gráficos simples.",
        "MotivoDaCriacao": "Criado pela Atari para popularizar jogos eletrônicos.",
        "MecanicasPrincipais": "Física de rebote, pontuação.",
        "InovacoesTecnologicas": "Popularizou os videogames em massa.",
        "ImpactoCulturalOuComercial": "Popularizou os videogames",
        "Genero": "Esporte / Arcade",
        "ErasGeracoes": "Era Arcade",
        "Imagem": "https://cdn.dribbble.com/userupload/42228467/file/original-367d2cd0605f71ed452ca9ed0cfff563.gif"
    },
    {
        "Ano": 1975,
        "Jogo": "Adventure (Colossal Cave)",
        "HistoriaResumida": "Aventura em texto com exploração de cavernas.",
        "MotivoDaCriacao": "Criar experiência narrativa interativa.",
        "MecanicasPrincipais": "Texto, exploração, puzzles.",
        "InovacoesTecnologicas": "Primeiro adventure game.",
        "ImpactoCulturalOuComercial": "Fundou o gênero adventure em texto",
        "Genero": "Aventura em texto",
        "ErasGeracoes": "Era dos PCs iniciais",
        "Imagem": "https://worldofspectrum.org//pub/sinclair/screens/in-game/c/ColossalCaveAdventure.gif"
    },
    {
        "Ano": 1976,
        "Jogo": "Breakout",
        "HistoriaResumida": "Jogador destrói blocos com uma bola rebatida por uma barra.",
        "MotivoDaCriacao": "Criado por Atari com design de Steve Wozniak e Steve Jobs.",
        "MecanicasPrincipais": "Rebote, destruição de blocos, fases.",
        "InovacoesTecnologicas": "Inspiração para jogos de puzzle e ação.",
        "ImpactoCulturalOuComercial": "Influenciou jogos de puzzle e ação",
        "Genero": "Arcade / Puzzle",
        "ErasGeracoes": "Era Atari",
        "Imagem": "https://miro.medium.com/v2/resize:fit:960/1*anOvalO-uz_RthzTS7y5rg.gif"
    },
    {
        "Ano": 1978,
        "Jogo": "Space Invaders",
        "HistoriaResumida": "Defesa contra invasão alienígena com tiros verticais.",
        "MotivoDaCriacao": "Desenvolvido por Tomohiro Nishikado no Japão.",
        "MecanicasPrincipais": "Movimento lateral, tiro, avanço de inimigos.",
        "InovacoesTecnologicas": "Primeiro jogo com trilha sonora dinâmica e recordes.",
        "ImpactoCulturalOuComercial": "Popularizou jogos de tiro e recordes",
        "Genero": "Shooter / Arcade",
        "ErasGeracoes": "Era Atari",
        "Imagem": "https://img.itch.zone/aW1nLzMwNjc3ODkuZ2lm/original/p%2F94De.gif"
    },
    {
        "Ano": 1979,
        "Jogo": "MUD1",
        "HistoriaResumida": "Jogo multiplayer em texto com mundo persistente.",
        "MotivoDaCriacao": "Criar ambiente social e cooperativo online.",
        "MecanicasPrincipais": "MMO, narrativa, cooperação.",
        "InovacoesTecnologicas": "Primeiro jogo multiplayer online persistente.",
        "ImpactoCulturalOuComercial": "Primeiro MMO da história",
        "Genero": "RPG / Multiplayer texto",
        "ErasGeracoes": "Era dos PCs iniciais",
        "Imagem": "img/1979_MUD1.gif"
    },
    {
        "Ano": 1980,
        "Jogo": "Pac-Man",
        "HistoriaResumida": "Personagem come pontos em labirinto evitando fantasmas.",
        "MotivoDaCriacao": "Criado para atrair público feminino aos arcades.",
        "MecanicasPrincipais": "IA dos fantasmas, power-ups, labirinto.",
        "InovacoesTecnologicas": "Personagem icônico e IA diferenciada.",
        "ImpactoCulturalOuComercial": "Ícone cultural global, atraiu público feminino",
        "Genero": "Arcade / Maze",
        "ErasGeracoes": "Era de Ouro dos Arcades",
        "Imagem": "https://i.pinimg.com/originals/2c/bd/99/2cbd9945ebb5a2069f18c8e82d69bb04.gif"
    },
    {
        "Ano": 1981,
        "Jogo": "Donkey Kong",
        "HistoriaResumida": "Mario salva Pauline de um gorila em plataformas.",
        "MotivoDaCriacao": "Primeiro jogo com Mario, criado por Shigeru Miyamoto.",
        "MecanicasPrincipais": "Plataformas, obstáculos, narrativa simples.",
        "InovacoesTecnologicas": "Introdução de narrativa e personagem recorrente.",
        "ImpactoCulturalOuComercial": "Introduziu Mario e narrativa simples",
        "Genero": "Plataforma / Arcade",
        "ErasGeracoes": "Era de Ouro dos Arcades",
        "Imagem": "https://i.makeagif.com/media/11-20-2015/OaAVZm.gif"
    },
    {
        "Ano": 1981,
        "Jogo": "Frogger",
        "HistoriaResumida": "Sapo atravessa ruas e rios evitando obstáculos.",
        "MotivoDaCriacao": "Criar jogo com desafio de timing e movimento.",
        "MecanicasPrincipais": "Movimento, padrões, pontuação.",
        "InovacoesTecnologicas": "Mecânicas de timing e padrões.",
        "ImpactoCulturalOuComercial": "Mecânica de timing influente",
        "Genero": "Arcade / Ação",
        "ErasGeracoes": "Era de Ouro dos Arcades",
        "Imagem": "img/1981_Frogger.gif"
    },
    {
        "Ano": 1982,
        "Jogo": "Pitfall!",
        "HistoriaResumida": "Aventura em selva com obstáculos e tesouros.",
        "MotivoDaCriacao": "Criado por David Crane para o Atari 2600.",
        "MecanicasPrincipais": "Plataformas, tempo, exploração.",
        "InovacoesTecnologicas": "Um dos primeiros jogos de aventura com progressão.",
        "ImpactoCulturalOuComercial": "Primeiro grande sucesso de aventura em consoles",
        "Genero": "Plataforma / Aventura",
        "ErasGeracoes": "Era Atari",
        "Imagem": "img/1982_Pitfall!.gif"
    },
    {
        "Ano": 1983,
        "Jogo": "Mario Bros",
        "HistoriaResumida": "Mario e Luigi enfrentam criaturas em esgotos.",
        "MotivoDaCriacao": "Introduzir cooperação e competição em plataforma.",
        "MecanicasPrincipais": "Plataformas, cooperação, pontuação.",
        "InovacoesTecnologicas": "Jogabilidade simultânea para dois jogadores.",
        "ImpactoCulturalOuComercial": "Cooperação e competição simultânea",
        "Genero": "Plataforma / Arcade",
        "ErasGeracoes": "Era Atari / NES",
        "Imagem": "https://i.makeagif.com/media/9-05-2018/G34cQV.gif"
    },
    {
        "Ano": 1983,
        "Jogo": "Dragon's Lair",
        "HistoriaResumida": "Aventura animada com decisões rápidas.",
        "MotivoDaCriacao": "Usar animação de qualidade cinematográfica.",
        "MecanicasPrincipais": "QTE, narrativa visual.",
        "InovacoesTecnologicas": "Laserdisc e animação fluida.",
        "ImpactoCulturalOuComercial": "Animação cinematográfica com laserdisc",
        "Genero": "Aventura interativa",
        "ErasGeracoes": "Era Laserdisc",
        "Imagem": "https://www.c64-wiki.com/images/b/b6/DragonsLair_3.gif"
    },
    {
        "Ano": 1984,
        "Jogo": "Elite",
        "HistoriaResumida": "Simulação espacial com comércio e combate.",
        "MotivoDaCriacao": "Criado por David Braben e Ian Bell.",
        "MecanicasPrincipais": "Mundo aberto, economia, combate espacial.",
        "InovacoesTecnologicas": "Gráficos 3D vetoriais e universo persistente.",
        "ImpactoCulturalOuComercial": "Universo aberto e comércio espacial",
        "Genero": "Simulação / Aventura",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "https://sidneyblaylockjr.wordpress.com/wp-content/uploads/2020/07/elite_animation.gif"
    },
    {
        "Ano": 1985,
        "Jogo": "Super Mario Bros",
        "HistoriaResumida": "Mario deve salvar a Princesa Peach em um mundo de fantasia.",
        "MotivoDaCriacao": "Expandir o universo de Mario com um jogo de plataforma mais complexo.",
        "MecanicasPrincipais": "Plataformas, power-ups, fases secretas.",
        "InovacoesTecnologicas": "Scroll lateral fluido e design de fases inovador.",
        "ImpactoCulturalOuComercial": "Revolucionou jogos de plataforma",
        "Genero": "Plataforma",
        "ErasGeracoes": "Era NES",
        "Imagem": "https://i.makeagif.com/media/7-27-2017/mKmjZT.gif"
    },
    {
        "Ano": 1985,
        "Jogo": "Tetris",
        "HistoriaResumida": "Encaixe de blocos para completar linhas.",
        "MotivoDaCriacao": "Criado por Alexey Pajitnov como puzzle matemático.",
        "MecanicasPrincipais": "Puzzle, tempo, pontuação.",
        "InovacoesTecnologicas": "Simplicidade viciante e adaptação para múltiplas plataformas.",
        "ImpactoCulturalOuComercial": "Puzzle universal, sucesso em múltiplas plataformas",
        "Genero": "Puzzle",
        "ErasGeracoes": "Era NES / PCs",
        "Imagem": "img/1985_Tetris.gif"
    },
    {
        "Ano": 1986,
        "Jogo": "The Legend of Zelda",
        "HistoriaResumida": "Aventura de Link para salvar o reino de Hyrule.",
        "MotivoDaCriacao": "Misturar ação com exploração e quebra-cabeças.",
        "MecanicasPrincipais": "Mundo aberto, inventário, progressão.",
        "InovacoesTecnologicas": "Sistema de salvamento e exploração não linear.",
        "ImpactoCulturalOuComercial": "Fundou o gênero de ação-aventura com exploração",
        "Genero": "Aventura / RPG",
        "ErasGeracoes": "Era NES",
        "Imagem": "img/1986_The_Legend_of_Zelda.gif"
    },
    {
        "Ano": 1986,
        "Jogo": "Metroid",
        "HistoriaResumida": "Samus explora planeta alienígena enfrentando criaturas e coletando upgrades.",
        "MotivoDaCriacao": "Criar jogo de ação com exploração não linear e protagonista feminina.",
        "MecanicasPrincipais": "Plataformas, exploração, progressão por habilidades.",
        "InovacoesTecnologicas": "Fundou o gênero metroidvania.",
        "ImpactoCulturalOuComercial": "Fundou o gênero metroidvania",
        "Genero": "Aventura / Plataforma",
        "ErasGeracoes": "Era NES",
        "Imagem": "https://64.media.tumblr.com/1835536f971d5e95fe3eace2c84b1f42/tumblr_inline_obhvtsW7Gt1r2gkqp_500.gif"
    },
    {
        "Ano": 1987,
        "Jogo": "Final Fantasy",
        "HistoriaResumida": "RPG com narrativa épica e batalhas por turnos.",
        "MotivoDaCriacao": "Salvar a empresa Square da falência com um RPG marcante.",
        "MecanicasPrincipais": "Batalhas por turnos, narrativa, evolução.",
        "InovacoesTecnologicas": "Início de uma das maiores franquias de RPG.",
        "ImpactoCulturalOuComercial": "Início de franquia icônica de RPG",
        "Genero": "RPG por turnos",
        "ErasGeracoes": "Era NES",
        "Imagem": "https://miro.medium.com/v2/resize:fit:1024/0*4cTKvKB-o_almm35.gif"
    },
    {
        "Ano": 1987,
        "Jogo": "Mega Man",
        "HistoriaResumida": "Robô azul enfrenta chefes e absorve seus poderes.",
        "MotivoDaCriacao": "Criar um herói carismático com jogabilidade desafiadora.",
        "MecanicasPrincipais": "Plataformas, armas variadas, progressão.",
        "InovacoesTecnologicas": "Sistema de escolha de fases e habilidades absorvíveis.",
        "ImpactoCulturalOuComercial": "Popularizou sistema de fases e poderes absorvíveis",
        "Genero": "Plataforma / Ação",
        "ErasGeracoes": "Era NES",
        "Imagem": "img/1987_Mega_Man.gif"
    },
    {
        "Ano": 1989,
        "Jogo": "SimCity",
        "HistoriaResumida": "Simulação de construção e gestão de cidade.",
        "MotivoDaCriacao": "Criar um jogo sem objetivo fixo, focado em criatividade.",
        "MecanicasPrincipais": "Gestão de recursos, planejamento urbano.",
        "InovacoesTecnologicas": "Simulação aberta e complexa.",
        "ImpactoCulturalOuComercial": "Fundou o gênero de simulação urbana",
        "Genero": "Simulação / Estratégia",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "https://media.rawg.io/media/resize/420/-/screenshots/2ab/2ab29c7ffcd80c803ee1eed2f64f1db7.jpg"
    },
    {
        "Ano": 1989,
        "Jogo": "Prince of Persia",
        "HistoriaResumida": "Aventura em plataformas com animações realistas.",
        "MotivoDaCriacao": "Mostrar o potencial de animação rotoscópica em jogos.",
        "MecanicasPrincipais": "Plataformas, combate, tempo.",
        "InovacoesTecnologicas": "Animações fluidas e narrativa cinematográfica.",
        "ImpactoCulturalOuComercial": "Animação fluida e narrativa cinematográfica",
        "Genero": "Plataforma / Aventura",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "https://upload.wikimedia.org/wikipedia/commons/2/28/Prince_of_Persia_1_-_MS-DOS_-_Gameplay_-_Potion.gif"
    },
    {
        "Ano": 1990,
        "Jogo": "Wing Commander",
        "HistoriaResumida": "Simulação espacial com narrativa e combate.",
        "MotivoDaCriacao": "Criar experiência cinematográfica em simulação.",
        "MecanicasPrincipais": "Combate, narrativa, escolha de missões.",
        "InovacoesTecnologicas": "Cutscenes com atores reais.",
        "ImpactoCulturalOuComercial": "Narrativa cinematográfica em simulação espacial",
        "Genero": "Simulação / Ação",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "img/1990_Wing_Commander.gif"
    },
    {
        "Ano": 1991,
        "Jogo": "Sonic the Hedgehog",
        "HistoriaResumida": "Mascote da SEGA em corridas velozes por fases coloridas.",
        "MotivoDaCriacao": "Concorrer com Mario e mostrar poder do Mega Drive.",
        "MecanicasPrincipais": "Velocidade, plataformas, fases variadas.",
        "InovacoesTecnologicas": "Velocidade como mecânica central.",
        "ImpactoCulturalOuComercial": "Mascote da SEGA, rival de Mario",
        "Genero": "Plataforma / Ação",
        "ErasGeracoes": "Era 16-bit (Mega Drive)",
        "Imagem": "https://i.gifer.com/QGxA.gif"
    },
    {
        "Ano": 1991,
        "Jogo": "Street Fighter II",
        "HistoriaResumida": "Luta entre personagens com estilos únicos.",
        "MotivoDaCriacao": "Evoluir o gênero de luta com personagens carismáticos.",
        "MecanicasPrincipais": "Combos, personagens variados, multiplayer.",
        "InovacoesTecnologicas": "Popularizou os jogos de luta competitivos.",
        "ImpactoCulturalOuComercial": "Popularizou os jogos de luta competitivos",
        "Genero": "Luta / Arcade",
        "ErasGeracoes": "Era 16-bit / Arcades",
        "Imagem": "img/1991_Street_Fighter_II.gif"
    },
    {
        "Ano": 1991,
        "Jogo": "Civilization",
        "HistoriaResumida": "Simulação de desenvolvimento de civilizações.",
        "MotivoDaCriacao": "Criar um jogo de estratégia baseado em história e progresso humano.",
        "MecanicasPrincipais": "Turnos, diplomacia, tecnologia.",
        "InovacoesTecnologicas": "Estratégia profunda e rejogabilidade infinita.",
        "ImpactoCulturalOuComercial": "Estratégia profunda baseada em história",
        "Genero": "Estratégia por turnos",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "https://procedural-generation.isaackarth.com/tumblr_files/tumblr_nyx03lmwXg1uo5d9jo2_540.gif"
    },
    {
        "Ano": 1991,
        "Jogo": "Another World",
        "HistoriaResumida": "Aventura sci-fi com narrativa visual e puzzles.",
        "MotivoDaCriacao": "Criar jogo artístico com animação fluida.",
        "MecanicasPrincipais": "Plataformas, narrativa ambiental.",
        "InovacoesTecnologicas": "Rotoscopia e storytelling visual.",
        "ImpactoCulturalOuComercial": "Narrativa visual sem diálogos, animação rotoscópica",
        "Genero": "Aventura / Cinemática",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "img/1991_another-world-out-of-this-world.gif"
    },
    {
        "Ano": 1992,
        "Jogo": "Wolfenstein 3D",
        "HistoriaResumida": "Soldado escapa de castelo nazista em primeira pessoa.",
        "MotivoDaCriacao": "Popularizar o gênero de tiro em primeira pessoa.",
        "MecanicasPrincipais": "FPS, coleta de itens, labirintos.",
        "InovacoesTecnologicas": "Pioneiro dos jogos de tiro em primeira pessoa.",
        "ImpactoCulturalOuComercial": "Pioneiro dos jogos de tiro em primeira pessoa",
        "Genero": "FPS",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1992,
        "Jogo": "Mortal Kombat",
        "HistoriaResumida": "Torneio de luta com personagens e fatalities.",
        "MotivoDaCriacao": "Criar um jogo de luta mais violento e realista.",
        "MecanicasPrincipais": "Combos, barra de vida, fatalities.",
        "InovacoesTecnologicas": "Digitalização de atores e violência gráfica.",
        "ImpactoCulturalOuComercial": "Polêmica e sucesso por violência gráfica",
        "Genero": "Luta / Arcade",
        "ErasGeracoes": "Era 16-bit / Arcades",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1993,
        "Jogo": "Doom",
        "HistoriaResumida": "Combate contra demônios em Marte.",
        "MotivoDaCriacao": "Evoluir o FPS com gráficos avançados e multiplayer.",
        "MecanicasPrincipais": "FPS, armas variadas, mapas complexos.",
        "InovacoesTecnologicas": "Multiplayer em rede e modding.",
        "ImpactoCulturalOuComercial": "Popularizou FPS e multiplayer em rede",
        "Genero": "FPS",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1993,
        "Jogo": "Myst",
        "HistoriaResumida": "Aventura gráfica com puzzles em ilha misteriosa.",
        "MotivoDaCriacao": "Criar uma experiência contemplativa e imersiva.",
        "MecanicasPrincipais": "Puzzles, exploração, narrativa ambiental.",
        "InovacoesTecnologicas": "Gráficos pré-renderizados e som ambiente.",
        "ImpactoCulturalOuComercial": "Narrativa contemplativa e puzzles visuais",
        "Genero": "Aventura / Puzzle",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1994,
        "Jogo": "Warcraft",
        "HistoriaResumida": "Estratégia em tempo real entre humanos e orcs.",
        "MotivoDaCriacao": "Criar um universo de fantasia para jogos de estratégia.",
        "MecanicasPrincipais": "RTS, coleta de recursos, combate.",
        "InovacoesTecnologicas": "Narrativa integrada ao RTS.",
        "ImpactoCulturalOuComercial": "Fundou universo de fantasia e base para WoW",
        "Genero": "RTS",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1994,
        "Jogo": "System Shock",
        "HistoriaResumida": "FPS com elementos de RPG e exploração.",
        "MotivoDaCriacao": "Misturar ação com narrativa e hacking.",
        "MecanicasPrincipais": "FPS, inventário, hacking.",
        "InovacoesTecnologicas": "Precursor dos immersive sims.",
        "ImpactoCulturalOuComercial": "Precursor dos immersive sims",
        "Genero": "FPS / RPG / Simulação",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1995,
        "Jogo": "Command & Conquer",
        "HistoriaResumida": "Conflito global entre facções militares.",
        "MotivoDaCriacao": "Expandir o gênero RTS com foco em guerra moderna.",
        "MecanicasPrincipais": "RTS, facções distintas, FMVs.",
        "InovacoesTecnologicas": "Uso de vídeos em tempo real e multiplayer online.",
        "ImpactoCulturalOuComercial": "Expansão do RTS com guerra moderna",
        "Genero": "RTS",
        "ErasGeracoes": "Era dos PCs",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1996,
        "Jogo": "Quake",
        "HistoriaResumida": "FPS com gráficos 3D e multiplayer online.",
        "MotivoDaCriacao": "Evoluir o FPS com motor gráfico 3D completo.",
        "MecanicasPrincipais": "FPS, física realista, multiplayer.",
        "InovacoesTecnologicas": "Motor gráfico 3D e suporte a mods.",
        "ImpactoCulturalOuComercial": "FPS 3D com multiplayer online e modding",
        "Genero": "FPS",
        "ErasGeracoes": "Era dos PCs / 3D",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1996,
        "Jogo": "Diablo",
        "HistoriaResumida": "RPG de ação em mundo sombrio.",
        "MotivoDaCriacao": "Criar um RPG acessível com combate em tempo real.",
        "MecanicasPrincipais": "Loot, progressão, combate em tempo real.",
        "InovacoesTecnologicas": "Sistema de loot e multiplayer online.",
        "ImpactoCulturalOuComercial": "RPG de ação com loot e multiplayer",
        "Genero": "RPG de ação",
        "ErasGeracoes": "Era dos PCs / 3D",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1996,
        "Jogo": "Super Mario 64",
        "HistoriaResumida": "Mario em aventura 3D para salvar Peach.",
        "MotivoDaCriacao": "Demonstrar o poder do Nintendo 64 com jogo 3D.",
        "MecanicasPrincipais": "Plataformas 3D, câmera livre, exploração.",
        "InovacoesTecnologicas": "Revolucionou o design de jogos 3D.",
        "ImpactoCulturalOuComercial": "Revolucionou jogos 3D de plataforma",
        "Genero": "Plataforma 3D",
        "ErasGeracoes": "Era Nintendo 64 / 3D",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1996,
        "Jogo": "Pokémon Red/Blue",
        "HistoriaResumida": "Treinadores capturam e batalham com criaturas.",
        "MotivoDaCriacao": "Criar universo de RPG com coleção e troca.",
        "MecanicasPrincipais": "RPG por turnos, coleção, evolução.",
        "InovacoesTecnologicas": "Troca via cabo e franquia multimídia.",
        "ImpactoCulturalOuComercial": "Início da franquia Pokémon e fenômeno global",
        "Genero": "RPG / Colecionável",
        "ErasGeracoes": "Era Game Boy",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1996,
        "Jogo": "Resident Evil",
        "HistoriaResumida": "Sobrevivência em mansão infestada de zumbis.",
        "MotivoDaCriacao": "Criar jogo de terror com foco em tensão e recursos limitados.",
        "MecanicasPrincipais": "Inventário limitado, puzzles, câmera fixa.",
        "InovacoesTecnologicas": "Fundador do gênero survival horror.",
        "ImpactoCulturalOuComercial": "Fundador do gênero survival horror",
        "Genero": "Terror / Aventura",
        "ErasGeracoes": "Era PlayStation / 3D",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1997,
        "Jogo": "Final Fantasy VII",
        "HistoriaResumida": "RPG com narrativa épica e gráficos 3D.",
        "MotivoDaCriacao": "Levar os RPGs japoneses ao público ocidental.",
        "MecanicasPrincipais": "Batalhas por turnos, narrativa cinematográfica.",
        "InovacoesTecnologicas": "CGs, narrativa profunda e trilha sonora marcante.",
        "ImpactoCulturalOuComercial": "RPG japonês com narrativa cinematográfica",
        "Genero": "RPG por turnos",
        "ErasGeracoes": "Era PlayStation / 3D",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1997,
        "Jogo": "Age of Empires",
        "HistoriaResumida": "Estratégia histórica desde a Idade da Pedra até a Era Imperial.",
        "MotivoDaCriacao": "Criar um RTS educativo com base em civilizações reais.",
        "MecanicasPrincipais": "RTS, evolução tecnológica, civilizações distintas.",
        "InovacoesTecnologicas": "Mistura de história e estratégia em tempo real.",
        "ImpactoCulturalOuComercial": "Mistura de história e estratégia em tempo real",
        "Genero": "RTS",
        "ErasGeracoes": "Era dos PCs / Windows 95",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1997,
        "Jogo": "Snake",
        "HistoriaResumida": "Jogo simples onde cobra cresce ao comer itens.",
        "MotivoDaCriacao": "Popularizar jogos em celulares Nokia.",
        "MecanicasPrincipais": "Movimento contínuo, pontuação.",
        "InovacoesTecnologicas": "Popularizou jogos em dispositivos móveis.",
        "ImpactoCulturalOuComercial": "Popularizou jogos em celulares",
        "Genero": "Arcade / Puzzle",
        "ErasGeracoes": "Era Mobile Inicial",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1998,
        "Jogo": "Zelda: Ocarina of Time",
        "HistoriaResumida": "Link viaja no tempo para salvar Hyrule.",
        "MotivoDaCriacao": "Levar Zelda ao mundo 3D com narrativa épica.",
        "MecanicasPrincipais": "Mundo aberto, combate, tempo, narrativa.",
        "InovacoesTecnologicas": "Design de mundo 3D e sistema de targeting (Z-targeting).",
        "ImpactoCulturalOuComercial": "Considerado um dos melhores jogos de todos os tempos",
        "Genero": "Aventura / RPG",
        "ErasGeracoes": "Era Nintendo 64 / 3D",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1998,
        "Jogo": "StarCraft",
        "HistoriaResumida": "Conflito entre três raças em universo sci-fi.",
        "MotivoDaCriacao": "Criar um RTS com equilíbrio entre facções.",
        "MecanicasPrincipais": "RTS, facções assimétricas, multiplayer competitivo.",
        "InovacoesTecnologicas": "Base dos eSports e multiplayer online.",
        "ImpactoCulturalOuComercial": "Base dos eSports e multiplayer competitivo",
        "Genero": "RTS",
        "ErasGeracoes": "Era dos PCs / eSports",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1998,
        "Jogo": "Half-Life",
        "HistoriaResumida": "Cientista enfrenta invasão alienígena após experimento.",
        "MotivoDaCriacao": "Evoluir narrativa em FPS com imersão.",
        "MecanicasPrincipais": "FPS, narrativa contínua, física.",
        "InovacoesTecnologicas": "Integração de história sem cutscenes.",
        "ImpactoCulturalOuComercial": "Revolucionou narrativa em FPS",
        "Genero": "FPS / Aventura",
        "ErasGeracoes": "Era dos PCs / 3D",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1999,
        "Jogo": "Counter-Strike",
        "HistoriaResumida": "Terroristas vs. antiterroristas em partidas multiplayer.",
        "MotivoDaCriacao": "Mod de Half-Life que virou fenômeno competitivo.",
        "MecanicasPrincipais": "FPS tático, economia, trabalho em equipe.",
        "InovacoesTecnologicas": "Base dos jogos competitivos online.",
        "ImpactoCulturalOuComercial": "Fundou FPS competitivo online",
        "Genero": "FPS / Tático",
        "ErasGeracoes": "Era dos PCs / eSports",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2000,
        "Jogo": "The Sims",
        "HistoriaResumida": "Simulação da vida cotidiana com personagens virtuais.",
        "MotivoDaCriacao": "Criar um jogo sem objetivos fixos, focado em comportamento humano.",
        "MecanicasPrincipais": "Simulação, construção, relações sociais.",
        "InovacoesTecnologicas": "IA social e liberdade criativa.",
        "ImpactoCulturalOuComercial": "Simulação social com enorme apelo comercial",
        "Genero": "Simulação / Vida",
        "ErasGeracoes": "Era dos PCs / Casual",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2000,
        "Jogo": "Deus Ex",
        "HistoriaResumida": "Conspiração global em mundo cyberpunk com liberdade de abordagem.",
        "MotivoDaCriacao": "Misturar FPS, RPG e narrativa ramificada.",
        "MecanicasPrincipais": "RPG, FPS, escolhas, múltiplos caminhos.",
        "InovacoesTecnologicas": "Definiu o gênero immersive sim.",
        "ImpactoCulturalOuComercial": "Definiu o gênero immersive sim",
        "Genero": "FPS / RPG / Simulação",
        "ErasGeracoes": "Era dos PCs / Narrativa",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2001,
        "Jogo": "GTA III",
        "HistoriaResumida": "Mundo aberto com narrativa criminal em 3D.",
        "MotivoDaCriacao": "Revolucionar a franquia com liberdade total.",
        "MecanicasPrincipais": "Mundo aberto, narrativa, veículos, combate.",
        "InovacoesTecnologicas": "Mundo aberto 3D com liberdade de ação.",
        "ImpactoCulturalOuComercial": "Revolucionou mundo aberto em 3D",
        "Genero": "Ação / Mundo Aberto",
        "ErasGeracoes": "Era PlayStation 2 / 3D",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2003,
        "Jogo": "Second Life",
        "HistoriaResumida": "Mundo virtual onde usuários criam avatares e interagem socialmente.",
        "MotivoDaCriacao": "Criar um ambiente digital para expressão e economia virtual.",
        "MecanicasPrincipais": "Construção, economia, socialização.",
        "InovacoesTecnologicas": "Economia virtual e criação de conteúdo por usuários.",
        "ImpactoCulturalOuComercial": "Economia virtual e expressão digital",
        "Genero": "Simulação / Social",
        "ErasGeracoes": "Era dos PCs / Online",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2003,
        "Jogo": "Call of Duty (série)",
        "HistoriaResumida": "FPS militar com campanhas e multiplayer.",
        "MotivoDaCriacao": "Criar FPS realista com narrativa histórica.",
        "MecanicasPrincipais": "FPS, narrativa, progressão.",
        "InovacoesTecnologicas": "Definiu padrão dos FPS modernos.",
        "ImpactoCulturalOuComercial": "Definiu padrão dos FPS militares modernos",
        "Genero": "FPS / Militar",
        "ErasGeracoes": "Era dos PCs / Consoles",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2004,
        "Jogo": "World of Warcraft",
        "HistoriaResumida": "MMORPG em universo de fantasia com raças e classes.",
        "MotivoDaCriacao": "Expandir o universo Warcraft para o gênero MMO.",
        "MecanicasPrincipais": "RPG online, progressão, guildas.",
        "InovacoesTecnologicas": "Escala massiva e mundo persistente.",
        "ImpactoCulturalOuComercial": "MMORPG mais influente da história",
        "Genero": "MMORPG",
        "ErasGeracoes": "Era dos PCs / Online",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2005,
        "Jogo": "God of War",
        "HistoriaResumida": "Kratos busca vingança contra os deuses gregos.",
        "MotivoDaCriacao": "Criar um jogo de ação cinematográfico com mitologia.",
        "MecanicasPrincipais": "Hack and slash, narrativa épica, combos.",
        "InovacoesTecnologicas": "Combate fluido e narrativa integrada.",
        "ImpactoCulturalOuComercial": "Combate cinematográfico e mitologia",
        "Genero": "Ação / Hack and Slash",
        "ErasGeracoes": "Era PlayStation 2",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2005,
        "Jogo": "Guitar Hero",
        "HistoriaResumida": "Ritmo musical com guitarra controladora.",
        "MotivoDaCriacao": "Popularizar jogos musicais com periféricos.",
        "MecanicasPrincipais": "Ritmo, pontuação, multiplayer.",
        "InovacoesTecnologicas": "Mudou relação entre música e jogos.",
        "ImpactoCulturalOuComercial": "Popularizou jogos musicais com periféricos",
        "Genero": "Ritmo / Música",
        "ErasGeracoes": "Era PlayStation 2 / Cultura Pop",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2006,
        "Jogo": "Roblox",
        "HistoriaResumida": "Plataforma onde usuários criam e jogam jogos.",
        "MotivoDaCriacao": "Oferecer ambiente de criação acessível para jovens.",
        "MecanicasPrincipais": "Criação de jogos, multiplayer, economia virtual.",
        "InovacoesTecnologicas": "Ferramentas de desenvolvimento acessíveis.",
        "ImpactoCulturalOuComercial": "Plataforma de criação e jogos sociais",
        "Genero": "Sandbox / Social",
        "ErasGeracoes": "Era Web / Mobile",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2007,
        "Jogo": "Portal",
        "HistoriaResumida": "Jogador resolve puzzles com arma de portais.",
        "MotivoDaCriacao": "Inovar com mecânica de física e narrativa minimalista.",
        "MecanicasPrincipais": "Física, puzzles, narrativa ambiental.",
        "InovacoesTecnologicas": "Mecânica de portais e humor sutil.",
        "ImpactoCulturalOuComercial": "Mecânica de portais e narrativa minimalista",
        "Genero": "Puzzle / Física / Aventura",
        "ErasGeracoes": "Era dos PCs / Narrativa",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2007,
        "Jogo": "BioShock",
        "HistoriaResumida": "FPS com narrativa filosófica em cidade submersa.",
        "MotivoDaCriacao": "Misturar ação com crítica social e escolhas morais.",
        "MecanicasPrincipais": "FPS, poderes, narrativa ramificada.",
        "InovacoesTecnologicas": "Atmosfera imersiva e dilemas éticos.",
        "ImpactoCulturalOuComercial": "FPS com narrativa filosófica e atmosfera imersiva",
        "Genero": "FPS / Narrativo",
        "ErasGeracoes": "Era dos PCs / Consoles",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2008,
        "Jogo": "Braid",
        "HistoriaResumida": "Jogo de plataforma com manipulação do tempo.",
        "MotivoDaCriacao": "Criar uma experiência artística e reflexiva.",
        "MecanicasPrincipais": "Plataformas, tempo, narrativa fragmentada.",
        "InovacoesTecnologicas": "Narrativa não linear e estética única.",
        "ImpactoCulturalOuComercial": "Elevou o padrão dos jogos indie com narrativa não linear",
        "Genero": "Plataforma / Puzzle",
        "ErasGeracoes": "Era Indie / Xbox 360",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2008,
        "Jogo": "Dead Space",
        "HistoriaResumida": "Sobrevivência em nave infestada de monstros.",
        "MotivoDaCriacao": "Criar terror com combate estratégico.",
        "MecanicasPrincipais": "Dismemberment, HUD diegético, atmosfera.",
        "InovacoesTecnologicas": "HUD integrado ao ambiente e combate tático.",
        "ImpactoCulturalOuComercial": "Revolucionou o terror com HUD diegético e combate tático",
        "Genero": "Terror / Ação",
        "ErasGeracoes": "Era PS3 / Xbox 360",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2008,
        "Jogo": "Left 4 Dead",
        "HistoriaResumida": "Coop contra hordas de zumbis com IA adaptativa.",
        "MotivoDaCriacao": "Criar experiência cooperativa intensa.",
        "MecanicasPrincipais": "Coop, IA dinâmica, sobrevivência.",
        "InovacoesTecnologicas": "IA Director que adapta dificuldade.",
        "ImpactoCulturalOuComercial": "Coop intenso com IA adaptativa",
        "Genero": "Tiro / Coop",
        "ErasGeracoes": "Era PS3 / Xbox 360 / PC",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2009,
        "Jogo": "Minecraft",
        "HistoriaResumida": "Mundo aberto de blocos com construção e sobrevivência.",
        "MotivoDaCriacao": "Criado por Markus Persson como sandbox criativo.",
        "MecanicasPrincipais": "Construção, crafting, exploração.",
        "InovacoesTecnologicas": "Mundo gerado proceduralmente e liberdade total.",
        "ImpactoCulturalOuComercial": "Fenômeno global de criatividade e educação",
        "Genero": "Sandbox / Sobrevivência",
        "ErasGeracoes": "Era Indie / Multiplataforma",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2009,
        "Jogo": "Angry Birds",
        "HistoriaResumida": "Jogador lança pássaros para destruir estruturas.",
        "MotivoDaCriacao": "Criar jogo casual com física divertida.",
        "MecanicasPrincipais": "Física, fases, personagens variados.",
        "InovacoesTecnologicas": "Popularização de jogos mobile com design simples.",
        "ImpactoCulturalOuComercial": "Popularizou jogos mobile com física divertida",
        "Genero": "Puzzle / Física",
        "ErasGeracoes": "Era Mobile / Casual",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2009,
        "Jogo": "FarmVille",
        "HistoriaResumida": "Simulação de fazenda com interação social.",
        "MotivoDaCriacao": "Criar jogo social para Facebook com mecânicas de tempo.",
        "MecanicasPrincipais": "Gestão de tempo, socialização, progressão.",
        "InovacoesTecnologicas": "Integração com redes sociais e microtransações.",
        "ImpactoCulturalOuComercial": "Jogos sociais e microtransações no Facebook",
        "Genero": "Simulação / Social",
        "ErasGeracoes": "Era Web / Social Gaming",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2009,
        "Jogo": "League of Legends",
        "HistoriaResumida": "Duas equipes competem em arena com heróis únicos.",
        "MotivoDaCriacao": "Popularizar o gênero MOBA com acesso gratuito e foco competitivo.",
        "MecanicasPrincipais": "MOBA, progressão por partida, cooperação.",
        "InovacoesTecnologicas": "Base dos eSports modernos e modelo free-to-play.",
        "ImpactoCulturalOuComercial": "Base dos eSports modernos e modelo free-to-play",
        "Genero": "MOBA",
        "ErasGeracoes": "Era PC / eSports",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2010,
        "Jogo": "Heavy Rain",
        "HistoriaResumida": "Thriller interativo sobre sequestro e decisões morais.",
        "MotivoDaCriacao": "Criar uma experiência narrativa cinematográfica.",
        "MecanicasPrincipais": "Narrativa ramificada, QTE, múltiplos finais.",
        "InovacoesTecnologicas": "Emoção e narrativa interativa com captura de movimentos.",
        "ImpactoCulturalOuComercial": "Narrativa interativa cinematográfica",
        "Genero": "Aventura / Interativo",
        "ErasGeracoes": "Era PS3 / Narrativa",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2010,
        "Jogo": "Limbo",
        "HistoriaResumida": "Garoto busca irmã em mundo sombrio e minimalista.",
        "MotivoDaCriacao": "Criar experiência artística com narrativa ambiental.",
        "MecanicasPrincipais": "Plataformas, física, narrativa implícita.",
        "InovacoesTecnologicas": "Estética monocromática e narrativa subjetiva.",
        "ImpactoCulturalOuComercial": "Estética minimalista e narrativa ambiental",
        "Genero": "Plataforma / Puzzle",
        "ErasGeracoes": "Era Indie / Xbox 360",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2011,
        "Jogo": "The Elder Scrolls V: Skyrim",
        "HistoriaResumida": "Aventura épica em mundo aberto de fantasia.",
        "MotivoDaCriacao": "Expandir a franquia Elder Scrolls com liberdade total.",
        "MecanicasPrincipais": "RPG, mundo aberto, exploração, crafting.",
        "InovacoesTecnologicas": "Mundo aberto expansivo e modding massivo.",
        "ImpactoCulturalOuComercial": "RPG de mundo aberto com liberdade total",
        "Genero": "RPG / Mundo Aberto",
        "ErasGeracoes": "Era PS3 / Xbox 360 / PC",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2011,
        "Jogo": "Portal 2",
        "HistoriaResumida": "Continuação com puzzles mais complexos e narrativa envolvente.",
        "MotivoDaCriacao": "Expandir o universo de Portal com coop e história.",
        "MecanicasPrincipais": "Física, coop, narrativa.",
        "InovacoesTecnologicas": "Coop criativo e humor refinado.",
        "ImpactoCulturalOuComercial": "Coop criativo e puzzles com física",
        "Genero": "Puzzle / Coop / Física",
        "ErasGeracoes": "Era PC / Consoles",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2011,
        "Jogo": "Dark Souls",
        "HistoriaResumida": "Aventura sombria com dificuldade elevada.",
        "MotivoDaCriacao": "Criar um jogo desafiador com narrativa indireta.",
        "MecanicasPrincipais": "RPG de ação, combate tático, morte como aprendizado.",
        "InovacoesTecnologicas": "Design de mundo interconectado e dificuldade como mecânica.",
        "ImpactoCulturalOuComercial": "Fundou o gênero soulslike com dificuldade elevada",
        "Genero": "RPG de ação / Aventura",
        "ErasGeracoes": "Era PS3 / Xbox 360",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2011,
        "Jogo": "Journey",
        "HistoriaResumida": "Aventura emocional com coop anônimo.",
        "MotivoDaCriacao": "Criar experiência sensorial e emocional.",
        "MecanicasPrincipais": "Coop, narrativa ambiental, exploração.",
        "InovacoesTecnologicas": "Multiplayer anônimo e storytelling sem palavras.",
        "ImpactoCulturalOuComercial": "Storytelling emocional e multiplayer anônimo",
        "Genero": "Aventura / Experimental",
        "ErasGeracoes": "Era PS3 / Indie",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2012,
        "Jogo": "Candy Crush Saga",
        "HistoriaResumida": "Puzzle de combinar doces com progressão por fases.",
        "MotivoDaCriacao": "Criar jogo casual viciante com monetização.",
        "MecanicasPrincipais": "Puzzle, fases, boosters.",
        "InovacoesTecnologicas": "Monetização por microtransações e integração social.",
        "ImpactoCulturalOuComercial": "Popularizou monetização por microtransações",
        "Genero": "Puzzle / Casual",
        "ErasGeracoes": "Era Mobile / Social Gaming",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2013,
        "Jogo": "The Last of Us",
        "HistoriaResumida": "Sobrevivência em mundo pós-apocalíptico com foco emocional.",
        "MotivoDaCriacao": "Criar narrativa madura e emocional em jogo de ação.",
        "MecanicasPrincipais": "Stealth, crafting, narrativa cinematográfica.",
        "InovacoesTecnologicas": "Narrativa emocional e atuação de alto nível.",
        "ImpactoCulturalOuComercial": "Narrativa emocional e atuação de alto nível",
        "Genero": "Ação / Aventura / Terror",
        "ErasGeracoes": "Era PS3 / Cinemático",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2013,
        "Jogo": "GTA V",
        "HistoriaResumida": "Três protagonistas em mundo aberto com múltiplas atividades.",
        "MotivoDaCriacao": "Expandir GTA com múltiplas perspectivas e mundo vivo.",
        "MecanicasPrincipais": "Mundo aberto, narrativa, multiplayer online.",
        "InovacoesTecnologicas": "Mundo aberto detalhado e GTA Online.",
        "ImpactoCulturalOuComercial": "Mundo aberto detalhado e sucesso comercial massivo",
        "Genero": "Ação / Mundo Aberto",
        "ErasGeracoes": "Era PS3 / PS4 / Online",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2013,
        "Jogo": "Papers, Please",
        "HistoriaResumida": "Inspetor de imigração decide quem entra no país.",
        "MotivoDaCriacao": "Criticar regimes autoritários com mecânica burocrática.",
        "MecanicasPrincipais": "Gestão, tempo, moralidade.",
        "InovacoesTecnologicas": "Narrativa emergente e crítica social.",
        "ImpactoCulturalOuComercial": "Crítica social com mecânica burocrática",
        "Genero": "Simulação / Narrativo",
        "ErasGeracoes": "Era Indie / PC",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2015,
        "Jogo": "The Witcher 3: Wild Hunt",
        "HistoriaResumida": "Aventura de Geralt em mundo aberto com narrativa rica.",
        "MotivoDaCriacao": "Adaptar os livros com profundidade e liberdade.",
        "MecanicasPrincipais": "RPG, narrativa ramificada, mundo aberto.",
        "InovacoesTecnologicas": "Narrativa madura e mundo vivo.",
        "ImpactoCulturalOuComercial": "RPG com narrativa madura e mundo vivo",
        "Genero": "RPG / Mundo Aberto",
        "ErasGeracoes": "Era PS4 / Xbox One / PC",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2015,
        "Jogo": "Undertale",
        "HistoriaResumida": "RPG onde escolhas morais afetam tudo.",
        "MotivoDaCriacao": "Criar um RPG indie com foco em empatia e humor.",
        "MecanicasPrincipais": "Combate único, narrativa interativa, múltiplos finais.",
        "InovacoesTecnologicas": "Subversão de mecânicas tradicionais de RPG.",
        "ImpactoCulturalOuComercial": "Subverte mecânicas de RPG com foco em empatia",
        "Genero": "RPG / Indie / Narrativo",
        "ErasGeracoes": "Era Indie / PC",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2015,
        "Jogo": "PUBG",
        "HistoriaResumida": "Sobrevivência em arena com 100 jogadores.",
        "MotivoDaCriacao": "Popularizar o gênero battle royale.",
        "MecanicasPrincipais": "Battle royale, loot, zona segura.",
        "InovacoesTecnologicas": "Base para o boom dos jogos battle royale.",
        "ImpactoCulturalOuComercial": "Popularizou o gênero battle royale",
        "Genero": "Battle Royale / Tiro",
        "ErasGeracoes": "Era PC / Online / eSports",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2015,
        "Jogo": "Rocket League",
        "HistoriaResumida": "Futebol com carros em arenas futuristas.",
        "MotivoDaCriacao": "Misturar esportes com ação arcade.",
        "MecanicasPrincipais": "Física, multiplayer, competição.",
        "InovacoesTecnologicas": "Mecânica única e sucesso em eSports.",
        "ImpactoCulturalOuComercial": "Mistura única de futebol com carros",
        "Genero": "Esporte / Ação / Arcade",
        "ErasGeracoes": "Era PS4 / eSports",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2016,
        "Jogo": "Pokémon GO",
        "HistoriaResumida": "Jogador captura Pokémon no mundo real usando realidade aumentada.",
        "MotivoDaCriacao": "Misturar nostalgia com tecnologia móvel e RA.",
        "MecanicasPrincipais": "RA, geolocalização, coleta.",
        "InovacoesTecnologicas": "Popularizou RA em jogos mobile.",
        "ImpactoCulturalOuComercial": "Popularizou realidade aumentada em jogos mobile",
        "Genero": "RA / Colecionável / Casual",
        "ErasGeracoes": "Era Mobile / RA",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2016,
        "Jogo": "Inside",
        "HistoriaResumida": "Aventura sombria com puzzles e narrativa implícita.",
        "MotivoDaCriacao": "Evoluir conceito de Limbo com mais profundidade.",
        "MecanicasPrincipais": "Plataformas, física, narrativa ambiental.",
        "InovacoesTecnologicas": "Design minimalista e storytelling ambiental.",
        "ImpactoCulturalOuComercial": "Referência em storytelling ambiental e design minimalista",
        "Genero": "Plataforma / Puzzle / Terror",
        "ErasGeracoes": "Era Indie / PC / Consoles",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2017,
        "Jogo": "Fortnite",
        "HistoriaResumida": "Battle royale com construção e estética cartunesca.",
        "MotivoDaCriacao": "Criar alternativa ao PUBG com mecânicas únicas.",
        "MecanicasPrincipais": "Battle royale, construção, eventos ao vivo.",
        "InovacoesTecnologicas": "Eventos interativos e integração com cultura pop.",
        "ImpactoCulturalOuComercial": "Fenômeno cultural com eventos ao vivo e integração pop",
        "Genero": "Battle Royale / Construção",
        "ErasGeracoes": "Era Crossplay / Cultura Pop",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2017,
        "Jogo": "Zelda: Breath of the Wild",
        "HistoriaResumida": "Link explora mundo aberto com liberdade total.",
        "MotivoDaCriacao": "Reinventar a franquia com foco em exploração.",
        "MecanicasPrincipais": "Mundo aberto, física, crafting.",
        "InovacoesTecnologicas": "Liberdade de exploração e física emergente.",
        "ImpactoCulturalOuComercial": "Redefiniu mundo aberto com liberdade total",
        "Genero": "Aventura / RPG / Mundo Aberto",
        "ErasGeracoes": "Era Switch / Exploração",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2017,
        "Jogo": "Hollow Knight",
        "HistoriaResumida": "Cavaleiro explora mundo subterrâneo em metroidvania.",
        "MotivoDaCriacao": "Criar jogo indie desafiador com estética sombria.",
        "MecanicasPrincipais": "Plataformas, combate, exploração.",
        "InovacoesTecnologicas": "Design refinado e profundidade narrativa.",
        "ImpactoCulturalOuComercial": "Elevou padrão dos metroidvanias indie",
        "Genero": "Plataforma / Aventura / RPG",
        "ErasGeracoes": "Era Indie / PC / Consoles",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2018,
        "Jogo": "Red Dead Redemption 2",
        "HistoriaResumida": "História de fora-da-lei no Velho Oeste com narrativa profunda.",
        "MotivoDaCriacao": "Expandir universo de RDR com realismo e emoção.",
        "MecanicasPrincipais": "Narrativa, mundo vivo, simulação.",
        "InovacoesTecnologicas": "Realismo gráfico e comportamento de NPCs.",
        "ImpactoCulturalOuComercial": "Narrativa profunda e realismo gráfico",
        "Genero": "Ação / Aventura / Mundo Aberto",
        "ErasGeracoes": "Era PS4 / Cinemático",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2020,
        "Jogo": "Among Us",
        "HistoriaResumida": "Tripulantes tentam descobrir impostores em nave.",
        "MotivoDaCriacao": "Criar jogo social simples e divertido.",
        "MecanicasPrincipais": "Dedução social, cooperação, traição.",
        "InovacoesTecnologicas": "Popularização por streamers e simplicidade viral.",
        "ImpactoCulturalOuComercial": "Viralização por streamers e mecânica social simples",
        "Genero": "Social / Dedução / Party Game",
        "ErasGeracoes": "Era Mobile / Streamers",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2020,
        "Jogo": "Hades",
        "HistoriaResumida": "Zagreus tenta escapar do submundo enfrentando criaturas mitológicas.",
        "MotivoDaCriacao": "Misturar narrativa com roguelike fluido.",
        "MecanicasPrincipais": "Roguelike, narrativa dinâmica, combate ágil.",
        "InovacoesTecnologicas": "Narrativa integrada ao loop de repetição.",
        "ImpactoCulturalOuComercial": "Roguelike com narrativa integrada e combate fluido",
        "Genero": "Roguelike / Ação / RPG",
        "ErasGeracoes": "Era Indie / PC / Consoles",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2020,
        "Jogo": "Call of Duty: Warzone",
        "HistoriaResumida": "Battle royale com armas modernas e progressão.",
        "MotivoDaCriacao": "Expandir franquia CoD para o gênero battle royale.",
        "MecanicasPrincipais": "FPS, loot, zona segura, contratos.",
        "InovacoesTecnologicas": "Integração com CoD e atualizações constantes.",
        "ImpactoCulturalOuComercial": "Battle royale com integração à franquia CoD",
        "Genero": "FPS / Battle Royale",
        "ErasGeracoes": "Era Crossplay / eSports",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2020,
        "Jogo": "Ghost of Tsushima",
        "HistoriaResumida": "Samurai defende ilha contra invasão mongol.",
        "MotivoDaCriacao": "Criar jogo histórico com combate fluido e mundo aberto.",
        "MecanicasPrincipais": "Stealth, combate, narrativa.",
        "InovacoesTecnologicas": "Estética cinematográfica e ambientação histórica.",
        "ImpactoCulturalOuComercial": "Estética cinematográfica e combate fluido",
        "Genero": "Ação / Aventura / Mundo Aberto",
        "ErasGeracoes": "Era PS4 / Histórico",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2020,
        "Jogo": "Fall Guys",
        "HistoriaResumida": "Competição em minigames estilo battle royale.",
        "MotivoDaCriacao": "Criar battle royale acessível e não violento.",
        "MecanicasPrincipais": "Física, multiplayer, eliminação.",
        "InovacoesTecnologicas": "Viralização e battle royale casual.",
        "ImpactoCulturalOuComercial": "Battle royale não violento e viral",
        "Genero": "Party Game / Casual / Física",
        "ErasGeracoes": "Era Streamers / Casual",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2021,
        "Jogo": "It Takes Two",
        "HistoriaResumida": "Casal transformado em bonecos resolve puzzles para salvar relação.",
        "MotivoDaCriacao": "Criar jogo cooperativo com narrativa emocional.",
        "MecanicasPrincipais": "Coop obrigatória, narrativa, variedade de mecânicas.",
        "InovacoesTecnologicas": "Coop inovador e narrativa sobre relacionamentos.",
        "ImpactoCulturalOuComercial": "Coop obrigatório com narrativa sobre relacionamentos",
        "Genero": "Coop / Puzzle / Aventura",
        "ErasGeracoes": "Era PS5 / Coop Criativo",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2022,
        "Jogo": "Elden Ring",
        "HistoriaResumida": "Aventura sombria em mundo aberto com lore profunda.",
        "MotivoDaCriacao": "Criar mundo aberto com DNA de Dark Souls.",
        "MecanicasPrincipais": "RPG de ação, mundo aberto, dificuldade elevada.",
        "InovacoesTecnologicas": "Liberdade de exploração e design de mundo interconectado.",
        "ImpactoCulturalOuComercial": "Mundo aberto com DNA de Dark Souls",
        "Genero": "RPG de ação / Mundo Aberto",
        "ErasGeracoes": "Era Soulslike / PS5 / PC",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2023,
        "Jogo": "Baldur's Gate 3",
        "HistoriaResumida": "RPG baseado em D&D com narrativa ramificada e combate tático.",
        "MotivoDaCriacao": "Adaptar regras de D&D com profundidade narrativa.",
        "MecanicasPrincipais": "RPG tático, narrativa, coop.",
        "InovacoesTecnologicas": "Liberdade narrativa e fidelidade ao RPG de mesa.",
        "ImpactoCulturalOuComercial": "RPG tático com liberdade narrativa e coop",
        "Genero": "RPG / Tático / Narrativo",
        "ErasGeracoes": "Era PC / RPG de Mesa",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2023,
        "Jogo": "Zelda: Tears of the Kingdom",
        "HistoriaResumida": "Continuação com novas mecânicas de construção e exploração aérea.",
        "MotivoDaCriacao": "Expandir universo de Breath of the Wild com criatividade.",
        "MecanicasPrincipais": "Física, construção, exploração vertical.",
        "InovacoesTecnologicas": "Mecânica de fusão de objetos e liberdade criativa.",
        "ImpactoCulturalOuComercial": "Expansão criativa de Breath of the Wild",
        "Genero": "Aventura / RPG / Construção",
        "ErasGeracoes": "Era Switch / Criatividade",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 2023,
        "Jogo": "Alan Wake II",
        "HistoriaResumida": "Escritor enfrenta horrores em narrativa interativa.",
        "MotivoDaCriacao": "Evoluir o gênero de terror psicológico com narrativa complexa.",
        "MecanicasPrincipais": "Terror, narrativa dual, combate.",
        "InovacoesTecnologicas": "Visual cinematográfico e narrativa interativa profunda.",
        "ImpactoCulturalOuComercial": "Terror psicológico com narrativa interativa profunda",
        "Genero": "Terror / Aventura / Narrativo",
        "ErasGeracoes": "Era Cinemático / PS5 / PC",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    }
]