const jogos = [
    {
        "Ano": 1972,
        "Jogo": "Pong",
        "HistoriaResumida": "Um dos primeiros jogos eletrônicos de arcade, simulando um jogo de tênis de mesa.",
        "MotivoDaCriacao": "Demonstrar a viabilidade comercial de jogos eletrônicos.",
        "MecanicasPrincipais": "Controle simples de uma barra para rebater a bola.",
        "InovacoesTecnologicas": "Uso de gráficos simples em tempo real para interação.",
        "ImpactoCulturalOuComercial": "Abriu as portas para a indústria de jogos eletrônicos.",
        "Genero": "Arcade",
        "ErasGeracoes": "Primeira geração de jogos eletrônicos",
        "Imagem": "https://s2-techtudo.glbimg.com/FC6t208Lmpof-iKNM_ACooOZk5s=/0x0:695x335/1000x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/X/3/hPPBAGTbaNWstiGobUkg/2013-12-06-wall-e-300-heroes.png"
    },
    {
        "Ano": 1980,
        "Jogo": "Pac-Man",
        "HistoriaResumida": "Jogo de labirinto em que o jogador controla Pac-Man para comer todos os pontos.",
        "MotivoDaCriacao": "Criar um jogo acessível e divertido para todas as idades.",
        "MecanicasPrincipais": "Movimentação em labirinto e estratégia para evitar fantasmas.",
        "InovacoesTecnologicas": "IA básica para o movimento dos fantasmas.",
        "ImpactoCulturalOuComercial": "Grande sucesso comercial e símbolo cultural dos anos 80.",
        "Genero": "Arcade",
        "ErasGeracoes": "Segunda geração de jogos eletrônicos",
        "Imagem": "https://www.techtudo.com.br/noticias/2013/12/genericos-de-lol-e-super-mario-veja-jogos-chineses-que-copiam-famosos.ghtml"
    },
    {
        "Ano": 1985,
        "Jogo": "Super Mario Bros.",
        "HistoriaResumida": "Plataforma onde Mario deve resgatar a princesa Peach.",
        "MotivoDaCriacao": "Apostar em jogos de plataforma com níveis desafiadores.",
        "MecanicasPrincipais": "Pular, correr e coletar moedas.",
        "InovacoesTecnologicas": "Rolar de tela lateral contínuo.",
        "ImpactoCulturalOuComercial": "Franquia icônica e sucesso comercial duradouro.",
        "Genero": "Plataforma",
        "ErasGeracoes": "Terceira geração de jogos eletrônicos",
        "Imagem": "https://www.techtudo.com.br/noticias/2013/12/genericos-de-lol-e-super-mario-veja-jogos-chineses-que-copiam-famosos.ghtml"
    },
    {
        "Ano": 1991,
        "Jogo": "Sonic the Hedgehog",
        "HistoriaResumida": "Jogo de plataforma com personagem rápido para competir com Mario.",
        "MotivoDaCriacao": "Criar um mascote para a Sega e competir com a Nintendo.",
        "MecanicasPrincipais": "Velocidade e coleta de anéis.",
        "InovacoesTecnologicas": "Gráficos rápidos e responsivos.",
        "ImpactoCulturalOuComercial": "Fez da Sega uma marca popular dos anos 90.",
        "Genero": "Plataforma",
        "ErasGeracoes": "Quarta geração de jogos eletrônicos",
        "Imagem": "https://www.techtudo.com.br/noticias/2013/12/genericos-de-lol-e-super-mario-veja-jogos-chineses-que-copiam-famosos.ghtml"
    },
    {
        "Ano": 1993,
        "Jogo": "Doom",
        "HistoriaResumida": "Jogo de tiro em primeira pessoa que definiu o gênero FPS.",
        "MotivoDaCriacao": "Explorar gráficos 3D e ação rápida.",
        "MecanicasPrincipais": "Exploração, tiro e sobrevivência.",
        "InovacoesTecnologicas": "Gráficos 3D em tempo real e multiplayer local.",
        "ImpactoCulturalOuComercial": "Popularizou o FPS e influenciou muitos jogos.",
        "Genero": "FPS",
        "ErasGeracoes": "Quinta geração de jogos eletrônicos",
        "Imagem": "https://www.techtudo.com.br/noticias/2013/12/genericos-de-lol-e-super-mario-veja-jogos-chineses-que-copiam-famosos.ghtml"
    },
    {
        "Ano": 1996,
        "Jogo": "Pokémon Red/Blue",
        "HistoriaResumida": "Jogo de RPG onde jogadores capturam e treinam criaturas.",
        "MotivoDaCriacao": "Criar uma franquia duradoura com elementos de coleção.",
        "MecanicasPrincipais": "Captura, batalha e troca de criaturas.",
        "InovacoesTecnologicas": "Sistema de troca via link cable.",
        "ImpactoCulturalOuComercial": "Criou uma franquia multimídia globalmente popular.",
        "Genero": "RPG",
        "ErasGeracoes": "Quinta geração de jogos eletrônicos",
        "Imagem": "https://www.techtudo.com.br/noticias/2013/12/genericos-de-lol-e-super-mario-veja-jogos-chineses-que-copiam-famosos.ghtml"
    },
    {
        "Ano": 2001,
        "Jogo": "Grand Theft Auto III",
        "HistoriaResumida": "Jogo de mundo aberto com narrativa madura.",
        "MotivoDaCriacao": "Oferecer liberdade ao jogador em um ambiente 3D.",
        "MecanicasPrincipais": "Exploração, missões e interação social.",
        "InovacoesTecnologicas": "Ambiente 3D em mundo aberto.",
        "ImpactoCulturalOuComercial": "Revolucionou jogos de mundo aberto.",
        "Genero": "Ação/Aventura",
        "ErasGeracoes": "Sexta geração de jogos eletrônicos",
        "Imagem": "https://www.techtudo.com.br/noticias/2013/12/genericos-de-lol-e-super-mario-veja-jogos-chineses-que-copiam-famosos.ghtml"
    },
    {
        "Ano": 2004,
        "Jogo": "World of Warcraft",
        "HistoriaResumida": "MMORPG com grande mundo persistente.",
        "MotivoDaCriacao": "Criar um jogo online de longa duração.",
        "MecanicasPrincipais": "Quests, raids e interação social.",
        "InovacoesTecnologicas": "Servidores escaláveis para milhares de jogadores.",
        "ImpactoCulturalOuComercial": "Popularizou MMORPGs no mainstream.",
        "Genero": "MMORPG",
        "ErasGeracoes": "Sétima geração de jogos eletrônicos",
        "Imagem": "https://www.techtudo.com.br/noticias/2013/12/genericos-de-lol-e-super-mario-veja-jogos-chineses-que-copiam-famosos.ghtml"
    },
    {
        "Ano": 2007,
        "Jogo": "Portal",
        "HistoriaResumida": "Jogo de puzzle e física em primeira pessoa.",
        "MotivoDaCriacao": "Explorar mecânicas inovadoras de portal.",
        "MecanicasPrincipais": "Criação de portais para resolver puzzles.",
        "InovacoesTecnologicas": "Uso avançado de física em jogos.",
        "ImpactoCulturalOuComercial": "Elogiado por design e inovação.",
        "Genero": "Puzzle",
        "ErasGeracoes": "Sétima geração de jogos eletrônicos",
        "Imagem": "https://www.techtudo.com.br/noticias/2013/12/genericos-de-lol-e-super-mario-veja-jogos-chineses-que-copiam-famosos.ghtml"
    },
    {
        "Ano": 2011,
        "Jogo": "Minecraft",
        "HistoriaResumida": "Jogo sandbox de construção e sobrevivência.",
        "MotivoDaCriacao": "Dar liberdade criativa ao jogador.",
        "MecanicasPrincipais": "Construção, exploração e sobrevivência.",
        "InovacoesTecnologicas": "Gráficos em blocos e mundo gerado proceduralmente.",
        "ImpactoCulturalOuComercial": "Um dos jogos mais vendidos e influentes.",
        "Genero": "Sandbox",
        "ErasGeracoes": "Oitava geração de jogos eletrônicos",
        "Imagem": "https://www.techtudo.com.br/noticias/2013/12/genericos-de-lol-e-super-mario-veja-jogos-chineses-que-copiam-famosos.ghtml"
    }
];
